server.port=8080

spring.data.mongodb.auto-index-creation=true

# Cache configuration
spring.cache.type=simple
spring.cache.cache-names=weatherCache
spring.cache.concurrent.time-to-live=1800000

# Disable security headers for weather endpoint
spring.security.filter.dispatcher-types=REQUEST

# Mail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Google OAuth2
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}

spring.profiles.active=dev