# MongoDB Atlas - Development
spring.data.mongodb.uri=${MONGO_PROD_URI}
spring.data.mongodb.auto-index-creation=true

# Weather API
weather.api.key=${WEATHER_API_KEY}

# Mail
spring.mail.username=${JAVA_EMAIL}
spring.mail.password=${JAVA_EMAIL_PASSWORD}

# Google OAuth2
google.redirect.uri=http://localhost:8080/auth/google/callback

# React development server
frontend.url=http://localhost:3000